# -*- coding: utf-8 -*-
"""Download the Reference Genome FASTA & GTF via NCBI & Ensembl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwQ4gMmxeWTVAxZAf7do7tvvLIZKPEKL

# **`Download the Reference Genome FASTA & GTF via NCBI & Ensembl`** using Python Google Colab
GENCODE : https://www.gencodegenes.org/
Ensembl: https://asia.ensembl.org/info/data/ftp/index.html


📺 Stay Connected

👉 For more tutorials and omics-related content, follow Future Omics on YouTube! 🔗 Follow like, share, and subscribe https://www.youtube.com/@Bioinformatics_Made_Easy 🎥✨
"""

import ipywidgets as widgets
from IPython.display import display
import urllib.request, os

# Predefined dictionary of species and assemblies
assemblies = {
    "Human (GRCh38)": {
        "fasta": "ftp://ftp.ensembl.org/pub/release-106/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz",
        "gtf":   "ftp://ftp.ensembl.org/pub/release-106/gtf/homo_sapiens/Homo_sapiens.GRCh38.106.gtf.gz"
    },
    "Mouse (GRCm39)": {
        "fasta": "ftp://ftp.ensembl.org/pub/release-106/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz",
        "gtf":   "ftp://ftp.ensembl.org/pub/release-106/gtf/mus_musculus/Mus_musculus.GRCm39.106.gtf.gz"
    },
    "Guinea Pig (Cavpor3.0)": {
        "fasta": "ftp://ftp.ensembl.org/pub/release-106/fasta/cavia_porcellus/dna/Cavia_porcellus.Cavpor3.0.dna.toplevel.fa.gz",
        "gtf":   "ftp://ftp.ensembl.org/pub/release-106/gtf/cavia_porcellus/Cavia_porcellus.Cavpor3.0.106.gtf.gz"
    }
}

# Dropdown menu
species_dropdown = widgets.Dropdown(
    options=list(assemblies.keys()),
    value="Guinea Pig (Cavpor3.0)",
    description="Species:"
)

download_button = widgets.Button(description="Download Reference Files")

def download_files(b):
    choice = assemblies[species_dropdown.value]
    out_dir = "reference_downloads"
    os.makedirs(out_dir, exist_ok=True)

    for ftype, url in choice.items():
        filename = os.path.join(out_dir, os.path.basename(url))
        print(f"Downloading {ftype} from {url} ...")
        urllib.request.urlretrieve(url, filename)
        print(f"Saved to {filename}")

download_button.on_click(download_files)

display(species_dropdown, download_button)

!wget ftp://ftp.ensembl.org/pub/release-106/fasta/cavia_porcellus/dna/Cavia_porcellus.Cavpor3.0.dna.toplevel.fa.gz

!wget ftp://ftp.ensembl.org/pub/release-106/gtf/cavia_porcellus/Cavia_porcellus.Cavpor3.0.106.gtf.gz